import { useState, useEffect, useCallback } from "react";
import { useSearchParams } from "react-router-dom";
import {
  listNotifications,
  markNotificationRead,
  type Notification,
  type NotificationType,
} from "../api/notifications";

const typeColors: Record<string, string> = {
  emergency: "bg-red-100 text-red-700",
  flight_reminder: "bg-blue-100 text-blue-700",
  accommodation_checkin: "bg-teal-100 text-teal-700",
  accommodation_checkout: "bg-teal-100 text-teal-700",
  transport_reminder: "bg-orange-100 text-orange-700",
  return_flight: "bg-indigo-100 text-indigo-700",
  broadcast: "bg-purple-100 text-purple-700",
  announcement: "bg-amber-100 text-amber-700",
};

const statusColors: Record<string, string> = {
  pending: "bg-gray-100 text-gray-700",
  scheduled: "bg-blue-100 text-blue-600",
  sent: "bg-emerald-100 text-emerald-700",
  failed: "bg-red-100 text-red-700",
  read: "bg-gray-50 text-gray-500",
};

export default function NotificationsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [total, setTotal] = useState(0);
  const [pages, setPages] = useState(1);
  const [loading, setLoading] = useState(true);

  const page = Number(searchParams.get("page")) || 1;
  const typeFilter = searchParams.get("type") || "";
  const statusFilter = searchParams.get("status") || "";

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const data = await listNotifications(page, 10, typeFilter || undefined, statusFilter || undefined);
      setNotifications(data.items);
      setTotal(data.total);
      setPages(data.pages);
    } finally {
      setLoading(false);
    }
  }, [page, typeFilter, statusFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  function goToPage(p: number) {
    const params: Record<string, string> = { page: String(p) };
    if (typeFilter) params.type = typeFilter;
    if (statusFilter) params.status = statusFilter;
    setSearchParams(params);
  }

  async function handleMarkRead(id: number) {
    try {
      await markNotificationRead(id);
      setNotifications((prev) =>
        prev.map((n) => n.id === id ? { ...n, status: "read" as const, read_at: new Date().toISOString() } : n)
      );
    } catch {}
  }

  return (
    <div>
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Notifications</h1>
          <p className="text-gray-500 text-sm mt-1">{total} notifications generated by the system</p>
        </div>
      </div>

      <div className="mb-4 flex flex-col sm:flex-row gap-2">
        <select
          value={typeFilter}
          onChange={(e) => {
            const v = e.target.value;
            const params: Record<string, string> = { page: "1" };
            if (v) params.type = v;
            if (statusFilter) params.status = statusFilter;
            setSearchParams(params);
          }}
          className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
        >
          <option value="">All Types</option>
          <option value="flight_reminder">Flight Reminder</option>
          <option value="accommodation_checkin">Check-in Reminder</option>
          <option value="accommodation_checkout">Check-out Reminder</option>
          <option value="transport_reminder">Transport Reminder</option>
          <option value="return_flight">Return Flight</option>
          <option value="emergency">Emergency</option>
          <option value="broadcast">Broadcast</option>
          <option value="announcement">Announcement</option>
        </select>
        <select
          value={statusFilter}
          onChange={(e) => {
            const v = e.target.value;
            const params: Record<string, string> = { page: "1" };
            if (typeFilter) params.type = typeFilter;
            if (v) params.status = v;
            setSearchParams(params);
          }}
          className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
        >
          <option value="">All Statuses</option>
          <option value="pending">Pending</option>
          <option value="scheduled">Scheduled</option>
          <option value="sent">Sent</option>
          <option value="failed">Failed</option>
          <option value="read">Read</option>
        </select>
        {(typeFilter || statusFilter) && (
          <button
            onClick={() => setSearchParams({ page: "1" })}
            className="px-4 py-2 border border-gray-300 rounded-lg text-sm text-gray-600 hover:bg-gray-50 transition-colors"
          >
            Clear
          </button>
        )}
      </div>

      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 bg-gray-50">
                <th className="text-left px-4 py-3 font-medium text-gray-600">Title</th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">Type</th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">Pilgrim</th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">Status</th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">Scheduled</th>
                <th className="text-left px-4 py-3 font-medium text-gray-600">Sent</th>
                <th className="text-right px-4 py-3 font-medium text-gray-600">Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={7} className="px-4 py-12 text-center text-gray-500">Loading...</td></tr>
              ) : notifications.length === 0 ? (
                <tr><td colSpan={7} className="px-4 py-12 text-center text-gray-500">No notifications found.</td></tr>
              ) : (
                notifications.map((n) => (
                  <tr key={n.id} className="border-b border-gray-100 hover:bg-gray-50">
                    <td className="px-4 py-3">
                      <div className="font-medium text-gray-900">{n.title}</div>
                      <div className="text-xs text-gray-500 line-clamp-1 mt-0.5">{n.message}</div>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`inline-block text-xs px-2 py-0.5 rounded-full capitalize ${typeColors[n.notification_type] || "bg-gray-100 text-gray-700"}`}>
                        {n.notification_type.replace(/_/g, " ")}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-600 text-xs">#{n.pilgrim_id}</td>
                    <td className="px-4 py-3">
                      <span className={`inline-block text-xs px-2 py-0.5 rounded-full capitalize ${statusColors[n.status] || "bg-gray-100 text-gray-700"}`}>
                        {n.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-600 text-xs">
                      {n.scheduled_time ? new Date(n.scheduled_time).toLocaleString() : "-"}
                    </td>
                    <td className="px-4 py-3 text-gray-600 text-xs">
                      {n.sent_at ? new Date(n.sent_at).toLocaleString() : "-"}
                    </td>
                    <td className="px-4 py-3 text-right">
                      {n.status !== "read" && (
                        <button onClick={() => handleMarkRead(n.id)}
                          className="text-emerald-600 hover:text-emerald-800 text-xs">
                          Mark Read
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {pages > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-gray-200">
            <span className="text-sm text-gray-500">Page {page} of {pages}</span>
            <div className="flex gap-1">
              <button onClick={() => goToPage(page - 1)} disabled={page <= 1}
                className="px-3 py-1 border border-gray-300 rounded text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50">Prev</button>
              <button onClick={() => goToPage(page + 1)} disabled={page >= pages}
                className="px-3 py-1 border border-gray-300 rounded text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50">Next</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
