"""add_preferences_table

Revision ID: 1662a8e6b9c5
Revises: 515279de4af5
Create Date: 2026-07-18 14:37:58.341593
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1662a8e6b9c5'
down_revision: Union[str, None] = '515279de4af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilgrim_id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.Enum('english', 'hausa', 'yoruba', 'igbo', 'arabic', name='preferredlanguage'), nullable=False),
    sa.Column('delivery_mode', sa.Enum('text', 'audio', 'text_and_audio', name='deliverymode'), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pilgrim_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pilgrim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    # ### end Alembic commands ###
