"""add_accommodations_table

Revision ID: 2468e9742051
Revises: 51d05a143419
Create Date: 2026-07-18 13:38:48.566840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2468e9742051'
down_revision: Union[str, None] = '51d05a143419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_table_if_not_exists(table_name, *args, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name not in insp.get_table_names():
        op.create_table(table_name, *args, **kwargs)


def _drop_table_if_exists(table_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names():
        op.drop_table(table_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_not_exists('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilgrim_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pilgrim_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_table_if_exists('accommodations')
    # ### end Alembic commands ###
