"""add_announcements_table

Revision ID: 515279de4af5
Revises: 93a3a084a615
Create Date: 2026-07-18 14:23:55.025650
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '515279de4af5'
down_revision: Union[str, None] = '93a3a084a615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_table_if_not_exists(table_name, *args, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name not in insp.get_table_names():
        op.create_table(table_name, *args, **kwargs)


def _drop_table_if_exists(table_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names():
        op.drop_table(table_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_not_exists('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('emergency', 'general', 'flight', 'accommodation', 'transport', name='announcementcategory'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='announcementpriority'), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_table_if_exists('announcements')
    # ### end Alembic commands ###
