"""add_flights_table

Revision ID: 51d05a143419
Revises: d1cd550981e6
Create Date: 2026-07-18 12:17:07.750003
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '51d05a143419'
down_revision: Union[str, None] = 'd1cd550981e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilgrim_id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=255), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=False),
    sa.Column('departure_airport', sa.String(length=100), nullable=False),
    sa.Column('arrival_airport', sa.String(length=100), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('gate', sa.String(length=20), nullable=True),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'boarding', 'departed', 'in_air', 'landed', 'cancelled', 'delayed', name='flightstatus'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pilgrim_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
