"""add_transports_table

Revision ID: 93a3a084a615
Revises: 2468e9742051
Create Date: 2026-07-18 13:49:14.507045
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '93a3a084a615'
down_revision: Union[str, None] = '2468e9742051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilgrim_id', sa.Integer(), nullable=False),
    sa.Column('bus_number', sa.String(length=50), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=False),
    sa.Column('driver_phone', sa.String(length=50), nullable=False),
    sa.Column('transport_type', sa.Enum('bus', 'van', 'taxi', 'car', 'other', name='transporttype'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pilgrim_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transports')
    # ### end Alembic commands ###
