"""add_users_and_refresh_tokens

Revision ID: 9a7e12bde1d6
Revises: 1f834885aeac
Create Date: 2026-07-18 10:25:07.798063
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9a7e12bde1d6'
down_revision: Union[str, None] = '1f834885aeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_table_if_not_exists(table_name, *args, **kwargs):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name not in insp.get_table_names():
        op.create_table(table_name, *args, **kwargs)


def _create_index_if_not_exists(index_name, table_name, columns, unique=False):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = [idx['name'] for idx in insp.get_indexes(table_name)]
    if index_name not in existing:
        op.create_index(index_name, table_name, columns, unique=unique)


def _drop_index_if_exists(index_name, table_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = [idx['name'] for idx in insp.get_indexes(table_name)]
    if index_name in existing:
        op.drop_index(index_name, table_name=table_name)


def _drop_table_if_exists(table_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if table_name in insp.get_table_names():
        op.drop_table(table_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_not_exists('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pilgrim', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_not_exists(op.f('ix_users_email'), 'users', ['email'], unique=True)
    _create_table_if_not_exists('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_not_exists(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_index_if_exists(op.f('ix_refresh_tokens_token'), 'refresh_tokens')
    _drop_table_if_exists('refresh_tokens')
    _drop_index_if_exists(op.f('ix_users_email'), 'users')
    _drop_table_if_exists('users')
    # ### end Alembic commands ###
