"""add_pilgrim_profile_fields

Revision ID: d1cd550981e6
Revises: 9a7e12bde1d6
Create Date: 2026-07-18 11:54:23.065979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd1cd550981e6'
down_revision: Union[str, None] = '9a7e12bde1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('passport_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'passport_number')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
