"""add_pilgrim_profile_fields

Revision ID: d1cd550981e6
Revises: 9a7e12bde1d6
Create Date: 2026-07-18 11:54:23.065979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd1cd550981e6'
down_revision: Union[str, None] = '9a7e12bde1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_column_if_not_exists(table_name, column):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = [c['name'] for c in insp.get_columns(table_name)]
    if column.name not in existing:
        op.add_column(table_name, column)


def _drop_column_if_exists(table_name, column_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = [c['name'] for c in insp.get_columns(table_name)]
    if column_name in existing:
        op.drop_column(table_name, column_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _add_column_if_not_exists('users', sa.Column('phone', sa.String(length=50), nullable=True))
    _add_column_if_not_exists('users', sa.Column('nationality', sa.String(length=100), nullable=True))
    _add_column_if_not_exists('users', sa.Column('passport_number', sa.String(length=50), nullable=True))
    _add_column_if_not_exists('users', sa.Column('emergency_contact', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_column_if_exists('users', 'emergency_contact')
    _drop_column_if_exists('users', 'passport_number')
    _drop_column_if_exists('users', 'nationality')
    _drop_column_if_exists('users', 'phone')
    # ### end Alembic commands ###
